[package]
name = "libp2p-echo"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Simple libp2p echo client/server application using QUIC"

[dependencies]
# Используем только основной пакет libp2p с нужными фичами
libp2p = { version = "0.55", features = ["full", "cbor", "ping", "tokio", "quic"] }
tokio = { version = "1.36", features = ["full", "rt", "rt-multi-thread", "macros"] }
futures = "0.3"
async-std = "1.12"
env_logger = "0.11.8"
log = "0.4"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "0.1.88"
ed25519-dalek = "2.0.0"
void = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"