[profile.default]
# Дефолтный таймаут для всех тестов
test-timeout = "20s"

# Параллельное выполнение тестов
test-threads = 1  # Для сетевых тестов лучше использовать 1 поток

# Повторение флакки-тестов
retries = 1

# Сохранение результатов для ускорения последующих запусков
cache-persistence = "cargo-metadata"

# Группировка тестов по приоритетам
[[profile.default.overrides]]
filter = 'package(xnetwork) & test(/node_core/)'
test-timeout = "10s"

[[profile.default.overrides]]
filter = 'package(xnetwork) & test(/core_connections/)'
test-timeout = "15s"

[[profile.default.overrides]]
filter = 'package(xnetwork) & test(/bootstrap/)'
test-timeout = "15s"

[[profile.default.overrides]]
filter = 'package(xnetwork) & test(/xauth/)'
test-timeout = "15s"

[[profile.default.overrides]]
filter = 'package(xnetwork) & test(/xstream/)'
test-timeout = "20s"

[[profile.default.overrides]]
filter = 'package(xnetwork) & test(/discovery/)'
test-timeout = "25s"

[[profile.default.overrides]]
filter = 'package(xnetwork) & test(/connectivity/)'
test-timeout = "30s"

# Профиль для быстрого тестирования
[profile.ci]
inherit = "default"
test-threads = 4  # В CI можно использовать больше потоков
retries = 2

# Профиль для отладки
[profile.debug]
inherit = "default"
test-threads = 1
retries = 0
