[profile.default]
# Дефолтный таймаут для всех тестов
test-timeout = "20s"

# Параллельное выполнение тестов
test-threads = 1  # Для сетевых тестов лучше использовать 1 поток

# Повторение флакки-тестов
retries = 1

# Сохранение результатов для ускорения последующих запусков
cache-persistence = "cargo-metadata"

# Группировка тестов по приоритетам
[[profile.default.overrides]]
filter = 'test(test_node_creation_and_startup) | test(test_peer_information) | test(test_node_diagnostics)'
test-timeout = "10s"

[[profile.default.overrides]]
filter = 'test(test_basic_connection_establishment) | test(test_connection_with_timeout_success) | test(test_disconnect_peer)'
test-timeout = "15s"

# Профиль для быстрого тестирования
[profile.ci]
inherit = "default"
test-threads = 4  # В CI можно использовать больше потоков
retries = 2

# Профиль для отладки
[profile.debug]
inherit = "default"
test-threads = 1
retries = 0
