[tool.poetry]
name = "p2p-kad-tests"
version = "0.1.0"
description = "Kademlia discovery testing for P2P network"
authors = ["Your Name <your.email@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.4.0"
pexpect = "^4.8.0"

[poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]