//! Handler traits and structures for processing commands and events

use async_trait::async_trait;
use libp2p::Swarm;
use libp2p::swarm::{NetworkBehaviour, SwarmEvent};

/// Trait for handling commands and events of a specific behaviour
#[async_trait::async_trait]
pub trait BehaviourHandler: Send  {
    /// Type of behaviour that this handler processes
    type Behaviour;

    /// Type of event generated by the behaviour
    type Event;

    /// Type of command for the behaviour
    type Command;

    /// Handle command for the behaviour
    async fn handle_cmd(&mut self, behaviour: &mut Self::Behaviour, cmd: Self::Command);

    /// Handle behaviour event (by reference)
    async fn handle_event(&mut self, behaviour: &mut Self::Behaviour, event: &Self::Event);
}

/// Trait for handling swarm-level commands and events
#[async_trait]
pub trait SwarmHandler<B>: Send + Default
where
    B: NetworkBehaviour,
{
    /// Type of commands that this SwarmHandler processes
    type Command: Send + 'static;

    /// Handle swarm-level command
    async fn handle_command(&mut self, swarm: &mut Swarm<B>, cmd: Self::Command);

    /// Handle swarm event
    async fn handle_event(&mut self, swarm: &mut Swarm<B>, event: &SwarmEvent<B::ToSwarm>);
}
